apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
  - image: 471574026140.dkr.ecr.us-east-2.amazonaws.com/test-psp-repo:latest
deploy:
  helm:
    releases:
    - name: skaffold-helm
      chartPath: charts
      artifactOverrides:
        image: 471574026140.dkr.ecr.us-east-2.amazonaws.com/test-psp-repo:latest